services:
  db:
    container_name: MySQLDatabase
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: Storefront
      MYSQL_USER: Cristhian
      MYSQL_PASSWORD: password22
      MYSQL_ROOT_PASSWORD: password22
    volumes:
        - db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - db


networks:
  db:
    driver: bridge

volumes:
  db: